## B"H


###
http://localhost:8000/api/v1/todos

###
GET http://localhost:8000/api/v1/todos/2

###
POST http://localhost:8000/api/v1/todos/
Content-Type: application/json

{
    "todo": "This is todo",
    "completed": true
}

###
PATCH http://localhost:8000/api/v1/todos/2
Content-Type: application/json

{
    "todo": "Workout 1/2 hour",
    "completed": true
}

###
DELETE http://localhost:8000/api/v1/todos/2

###
GET http://localhost:8000/api/v1/todos/search/1

######################
####    USERS 
######################

###
GET http://localhost:8000/api/v1/users

###
http://localhost:8000/api/v1/users/3

###
PATCH http://localhost:8000/api/v1/users/1
Content-Type: application/json

{
    "name": "Tommy"
}

###
DELETE http://localhost:8000/api/v1/users/6

###
GET http://localhost:8000/api/v1/users/search/Charles?