## B"H


###
http://localhost:8000/api/v1/todos

###
GET http://localhost:8000/api/v1/todos/6

###
POST http://localhost:8000/api/v1/todos/
Content-Type: application/json

{
    "todo": "This is todo",
    "completed": true
}

###
PATCH http://localhost:8000/api/v1/todos/6
Content-Type: application/json

{
    "todo": "Updated todo",
    "completed": true
}

###
DELETE http://localhost:8000/api/v1/todos/6

######################
####    USERS 
######################

###
GET http://localhost:8000/api/v1/users

###
http://localhost:8000/api/v1/users/6

###
PATCH http://localhost:8000/api/v1/users/6
Content-Type: application/json

{
    "firstName" : "Emily",
    "lastName" : "Smith"
}

###
DELETE http://localhost:8000/api/v1/users/6